name: 'Assign Issues To Project'
description: 'Assign issues to a given github project'
inputs:
  githubToken:
    description: 'the github token to use'
    required: true
    default: ''
  projectNumber:
    description: 'the number of the project to use'
    required: true
    default: ''
  orgName:
    description: 'the name of the organization to use'
    required: true
    default: ''
  repoName:
    description: 'the name of the repository'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install requirements
      run: |
        pip install -r ${{ github.action_path }}/requirements.txt
        python ${{ github.action_path }}/github_management.py
      shell: pwsh
      env:
        API_GITHUB_TOKEN: ${{ inputs.githubToken }}
        GITHUB_PROJECT_NUMBER: ${{ inputs.projectNumber }}
        GITHUB_REPO_NAMES: ${{ inputs.repoName }}
        GITHUB_ORG_NAME: ${{ inputs.orgName }}
